export function dashboardHTML(csrf: string) {
  return String.raw`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Professional Publisher</title><style>
:root{font:16px/1.5 system-ui;color:#182d33;background:#f5f3ec}*{box-sizing:border-box}body{margin:0}header{padding:24px 5%;border-bottom:1px solid #d3d8d3}h1{font-size:26px;margin:0}main{max-width:1350px;margin:28px auto;padding:0 24px}nav,.row{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:18px}button{border:1px solid #b8c8c0;background:white;border-radius:8px;padding:10px 14px;cursor:pointer;color:#175d4c;font:inherit;margin:4px}button.active{background:#175d4c;color:white}button:disabled{opacity:.45;cursor:default}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:18px}.card{background:white;padding:24px;border-radius:12px;border:1px solid #dce1db;overflow-wrap:anywhere}h3{margin:0 0 10px}pre{white-space:pre-wrap;font:inherit}input,textarea,select{width:100%;padding:10px;border:1px solid #b8c8c0;border-radius:6px;margin:6px 0 14px;font:inherit}textarea{min-height:110px}label{display:block}input[type=checkbox]{width:auto;margin-right:8px}img,video,iframe{max-width:100%}small{color:#586c65}#message{position:sticky;top:0;background:#ffefc9;padding:12px;display:none;z-index:2}a{color:#175d4c;margin-right:12px}.month{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:5px;margin:18px 0}.day{background:white;min-height:100px;padding:8px;border:1px solid #dce1db;border-radius:6px}.day button{font-size:12px;padding:4px;display:block;width:100%;text-align:left;margin:5px 0}.full{grid-column:1/-1}.compare{display:grid;grid-template-columns:1fr 1fr;gap:18px}details{margin:14px 0}summary{cursor:pointer}dialog{border:1px solid #b8c8c0;border-radius:12px;max-width:650px;width:95%}@media(max-width:650px){.month{overflow:auto;grid-template-columns:repeat(7,110px)}.compare{grid-template-columns:1fr}}
</style><header><small>YOUR VOICE. YOUR APPROVAL.</small><h1>Professional Publisher</h1></header><main><div id="message" role="status"></div><nav id="nav"></nav><section id="view"></section></main><script>
const csrf=${JSON.stringify(csrf)};
let data={},active='Calendar',selectedDraft='',studioIdentity='',month=new Date(),identities=[],fieldId=0;
const el=(tag,text)=>{const x=document.createElement(tag);if(text!==undefined)x.textContent=text;return x};
const card=(title,text)=>{const c=el('article');c.className='card';c.append(el('h3',title));if(text)c.append(el('pre',text));return c};
function message(text){const n=document.querySelector('#message');n.textContent=text;n.style.display='block'}
function button(parent,text,fn){const b=el('button',text);b.onclick=()=>Promise.resolve().then(fn).catch(e=>message(e.message));parent.append(b);return b}
function field(parent,name,type='text',value=''){const label=el('label',name),i=el(type==='textarea'?'textarea':'input');i.id='field-'+(++fieldId);label.htmlFor=i.id;if(type!=='textarea')i.type=type;i.value=value;parent.append(label,i);return i}
function check(parent,name,value=false){const l=el('label'),i=el('input');i.type='checkbox';i.checked=value;l.append(i,document.createTextNode(name));parent.append(l);return i}
function select(parent,label,options,value){const l=el('label',label),s=el('select');s.id='field-'+(++fieldId);l.htmlFor=s.id;for(const [v,t] of options){const o=el('option',t);o.value=v;s.append(o)}s.value=value;parent.append(l,s);return s}
async function request(path,body){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-Publisher-CSRF':csrf},body:JSON.stringify(body)});const value=await r.json();if(!r.ok)throw Error(value.message||'Action failed');return value}
async function post(path,body){const result=await request(path,body);message('Saved.');await load();return result}
async function load(){const r=await fetch('/state');if(!r.ok)throw Error('Dashboard session ended. Open a new link.');data=await r.json();render()}
function link(parent,text,url){const a=el('a',text);a.href=url;a.target='_blank';a.rel='noreferrer';parent.append(a);return a}
function modal(title){const d=el('dialog');d.append(el('h2',title));document.body.append(d);d.addEventListener('close',()=>d.remove());button(d,'Close',()=>d.close());d.showModal();return d}
function render(){const nav=document.querySelector('#nav');nav.replaceChildren();for(const t of ['Calendar','Ideas','Drafts','Slides','Voice Studio','Accounts']){const b=button(nav,t,()=>{active=t;render()});b.className=t===active?'active':''}const view=document.querySelector('#view');view.replaceChildren(el('h2',active));const grid=el('div');grid.className='grid';view.append(grid);
if(active==='Calendar')calendar(view,grid);if(active==='Drafts')drafts(grid);if(active==='Accounts')accounts(grid);if(active==='Voice Studio')studio(grid).catch(e=>message(e.message));
if(active==='Ideas'){const c=card('Capture an idea'),title=field(c,'Title'),notes=field(c,'Notes','textarea');button(c,'Save idea',()=>post('/idea',{idea:{title:title.value,notes:notes.value}}));grid.append(c);for(const i of data.ideas||[])grid.append(card(i.title,i.notes))}
if(active==='Slides'){for(const d of data.decks||[]){const c=card(d.title,'Version '+d.version+' · '+d.slides.length+' slides');const img=el('img');img.src='/asset?deck='+d.id+'&name=contact-sheet.png';img.alt='Contact sheet for '+d.title;img.onerror=()=>img.remove();c.append(img);button(c,'Inspect individual slides',()=>{const dialog=modal(d.title);d.slides.forEach((s,n)=>{const image=el('img');image.src='/asset?deck='+d.id+'&name=slide-'+String(n+1).padStart(2,'0')+'.png';image.alt='Slide '+(n+1)+': '+s.title;dialog.append(el('h3','Slide '+(n+1)),image)})});for(const name of ['deck.pdf','deck.pptx','source.json'])link(c,name,'/asset?deck='+d.id+'&name='+name);grid.append(c)}}}
function calendar(view,grid){view.prepend(el('p','Schedules require an installed worker and an awake, online computer. Missed jobs never publish late. Calendar dates use your browser time zone.'));
const controls=el('div');button(controls,'Previous month',()=>{month=new Date(month.getFullYear(),month.getMonth()-1,1);render()});controls.append(el('strong',month.toLocaleDateString(undefined,{month:'long',year:'numeric'})));button(controls,'Next month',()=>{month=new Date(month.getFullYear(),month.getMonth()+1,1);render()});view.insertBefore(controls,grid);
const cal=el('div');cal.className='month';for(const day of ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'])cal.append(el('strong',day));const first=new Date(month.getFullYear(),month.getMonth(),1);for(let i=0;i<first.getDay();i++)cal.append(el('div'));for(let n=1;n<=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();n++){const cell=el('div');cell.className='day';cell.append(el('strong',n));const date=new Date(month.getFullYear(),month.getMonth(),n);cell.ondragover=e=>e.preventDefault();cell.ondrop=e=>{e.preventDefault();const j=(data.schedules||[]).find(j=>j.id===e.dataTransfer.getData('text/plain'));if(j)reschedule(j,date)};for(const j of data.schedules||[]){if(new Date(j.dueAt).toDateString()!==date.toDateString())continue;const d=(data.drafts||[]).find(d=>d.id===j.draftId);const b=button(cell,(d?.text||'Post').slice(0,30)+' · '+j.state,()=>reschedule(j));b.draggable=j.state==='scheduled';b.ondragstart=e=>e.dataTransfer.setData('text/plain',j.id)}cal.append(cell)}view.insertBefore(cal,grid);
for(const j of data.schedules||[]){const d=(data.drafts||[]).find(d=>d.id===j.draftId),c=card(new Date(j.dueAt).toLocaleString()+' · '+j.state,(d?.text||j.draftId)+'\nZone: '+j.timeZone);if(j.state==='scheduled'){button(c,'Reschedule',()=>reschedule(j));button(c,'Cancel schedule',()=>post('/cancel',{id:j.id}))}grid.append(c)}for(const n of data.notifications||[])grid.append(card(n.message,'Desktop notification: '+(n.nativeStatus||'disabled')+(n.error?'\n'+JSON.stringify(n.error):'')))}
function reschedule(j,date){const d=(data.drafts||[]).find(d=>d.id===j.draftId),dialog=modal('Review schedule change');dialog.append(el('pre',(d?.text||'')+'\nDestination: '+(d?.author||'')+'\nCurrent: '+j.at+' · '+j.timeZone));if(j.state!=='scheduled'){dialog.append(el('p','Only pending jobs can be moved.'));return}let proposed=j.at;if(date){const hint=date.getFullYear()+'-'+String(date.getMonth()+1).padStart(2,'0')+'-'+String(date.getDate()).padStart(2,'0');proposed=hint+j.at.slice(10);dialog.append(el('p','Proposed calendar date: '+hint+'. Review the UTC offset for the publishing zone, especially across daylight-saving changes.'))}const at=field(dialog,'New ISO time including UTC offset','text',proposed),zone=field(dialog,'IANA time zone','text',j.timeZone);button(dialog,'Approve this new publication time',async()=>{await request('/reschedule',{id:j.id,schedule:{draftId:j.draftId,reviewDigest:j.reviewDigest,authorization:'User approved schedule in local dashboard for '+at.value+' '+zone.value,at:at.value,timeZone:zone.value}});dialog.close();await load();message('Schedule changed.')})}
function drafts(grid){const all=data.drafts||[];if(!all.length){grid.append(card('No drafts yet','Ask Codex or Claude to prepare a draft. It stays local until you approve publication.'));return}if(!all.some(d=>d.id===selectedDraft))selectedDraft=all[all.length-1].id;const list=card('Draft versions'),chooser=select(list,'Draft',all.map(d=>[d.id,(d.text||d.format).slice(0,70)+' · '+d.state]),selectedDraft);chooser.onchange=()=>{selectedDraft=chooser.value;render()};grid.append(list);const d=all.find(d=>d.id===selectedDraft),c=card('Review exact post','Destination: '+d.author+'\nVisibility: PUBLIC\nState: '+d.state);c.classList.add('full');grid.append(c);
const parent=(data.draft_revisions||[]).find(r=>r.id===d.id),old=all.find(x=>x.id===parent?.parentId);if(old){const diff=el('div');diff.className='compare';diff.append(card('Previous version',old.text),card('Current version',d.text));c.append(diff)}else c.append(el('pre',d.text));if(d.result)link(c,'View published post',d.result.url);if(d.error)c.append(el('pre',JSON.stringify(d.error)));
const options=new Map([[d.connectionId+'|'+d.author,d.connectionId+' · '+d.author]]);for(const i of identities)options.set(i.connectionId+'|'+i.author,i.name+' · '+i.author);for(const a of data.connections||[])if(a.member)options.set(a.id+'|'+a.member,a.name+' · '+a.member);button(c,'Refresh available destinations',async()=>{const result=await request('/capabilities',{});identities=result.connections.flatMap(c=>c.identities||[]);render()});
const dest=select(c,'Destination for the revision',[...options],d.connectionId+'|'+d.author),text=field(c,'Caption','textarea',d.text);text.maxLength=3000;const url=field(c,'Link-card URL (blank for none)','url',d.link?.url||''),title=field(c,'Link-card title','text',d.link?.title||''),description=field(c,'Link-card description','textarea',d.link?.description||'');let attachments=d.attachments.map((a,index)=>({...a,index})),dirty=false;const actions=[];const mark=()=>{dirty=true;for(const b of actions)b.disabled=true};for(const i of [dest,text,url,title,description])i.oninput=mark;const assets=el('div');c.append(assets);
function drawAssets(){assets.replaceChildren();attachments.forEach((a,index)=>{const row=card('Attachment '+(index+1),a.kind),assetUrl='/attachment?draft='+d.id+'&index='+a.index;if(a.kind==='image'){const img=el('img');img.src=assetUrl;img.alt=a.altText||a.title;row.append(img)}else link(row,'Inspect attachment',assetUrl);const caption=field(row,'Attachment title','text',a.title),alt=field(row,'Alt text','textarea',a.altText||'');caption.oninput=()=>{a.title=caption.value;mark()};alt.oninput=()=>{a.altText=alt.value;mark()};button(row,'Move earlier',()=>{if(index>0){[attachments[index-1],attachments[index]]=[attachments[index],attachments[index-1]];mark();drawAssets()}});button(row,'Move later',()=>{if(index<attachments.length-1){[attachments[index],attachments[index+1]]=[attachments[index+1],attachments[index]];mark();drawAssets()}});button(row,'Remove attachment',()=>{attachments.splice(index,1);mark();drawAssets()});assets.append(row)})}drawAssets();
button(c,'Save new revision',async()=>{const [connectionId,author]=dest.value.split('|'),result=await request('/revise',{id:d.id,digest:d.digest,draft:{connectionId,author,text:text.value,attachments:attachments.map(a=>({path:a.storedPath,title:a.title,altText:a.altText})),...(url.value?{link:{url:url.value,title:title.value,description:description.value||undefined}}:{})}});selectedDraft=result.id;await load();message('Revision saved. Review its destination, text and attachments before publication.')});
const checks=(data.review_checks||[]).find(x=>x.id===d.id&&x.digest===d.digest)||{},sources=field(c,'Source links / fact-check notes (one per line)','textarea',(checks.sources||[]).join('\n')),facts=check(c,'I checked the facts and sources',checks.factsChecked),media=check(c,'I inspected all attachments and slides',checks.attachmentsChecked),destination=check(c,'I checked the destination and PUBLIC visibility',checks.destinationChecked);
const saveChecks=()=>request('/review',{id:d.id,digest:d.digest,checks:{sources:sources.value.split('\n').filter(Boolean),factsChecked:facts.checked,attachmentsChecked:media.checked,destinationChecked:destination.checked}});
actions.push(button(c,'Save review checklist',()=>saveChecks().then(()=>message('Review checklist saved.'))));actions.push(button(c,'Approve this text for voice learning',()=>post('/approve-learning',{id:d.id,digest:d.digest,authorization:'User approved this exact text for learning in the local dashboard.'})));
const publish=button(c,'Publish this exact post publicly',async()=>{if(dirty)throw Error('Save and review the revision first.');if(!facts.checked||!media.checked||!destination.checked)throw Error('Complete the review checklist first.');if(!confirm('Publish the displayed saved post PUBLICLY to '+d.author+' now? This uploads its attachments.'))return;await saveChecks();publish.disabled=true;try{const result=await request('/publish',{id:d.id,digest:d.digest,authorization:'User clicked publish for this exact saved draft and destination in the local dashboard.'});await load();message(result.state==='published'?'Published. Receipt saved.':result.error?.message||result.nextAction||'Inspect the saved result before trying again.')}finally{publish.disabled=false}});actions.push(publish);if(!['draft','rejected'].includes(d.state))publish.disabled=true;c.append(el('p','Edits create a new version. Existing schedules keep their original draft. Learning approval and publishing approval are separate.'))}
function accounts(grid){const connect=card('Connect LinkedIn'),id=field(connect,'Account label','text','personal'),mode=select(connect,'Account type',[['personal','Personal profile'],['company','Company pages']],'personal');button(connect,'Start secure connection',async()=>{const result=await request('/connect',{id:id.value,mode:mode.value});link(connect,'Open private setup',result.url)});grid.append(connect);
for(const a of data.connections||[]){const c=card(a.name,'Account: '+a.id+'\nPermissions: '+a.scopes.join(', ')+'\nExpires: '+new Date(a.expiresAt).toLocaleString()+'\nRefresh: '+(a.refreshSupported?'granted':'not granted')+'\nStatus: '+(a.revoked?'disconnected':'connected'));button(c,'Reconnect',async()=>{const result=await request('/connect',{id:a.id,mode:a.mode});link(c,'Open private setup',result.url)});button(c,'Disconnect and remove credentials',async()=>{if(confirm('Disable '+a.id+', cancel its pending schedules and delete tracked credentials? Submitted posts cannot be recalled.'))await post('/disconnect',{id:a.id})});button(c,'Clean old credential generations',()=>post('/cleanup-credentials',{id:a.id}));if(a.member)button(c,'Remove voice data and brand',async()=>{if(confirm('Delete samples, voice history and brand for '+a.member+'? Drafts and receipts remain.'))await post('/clear-voice',{identity:a.member})});grid.append(c)}
const options=card('Local preferences');button(options,'Enable desktop notifications',()=>post('/notifications',{enabled:true}));button(options,'Disable desktop notifications',()=>post('/notifications',{enabled:false}));options.append(el('p','Notifications contain generic job outcomes. Your OS may require permission.'));grid.append(options);
const backup=card('Encrypted backup','Includes local drafts, voice, slides and assets. Credentials are excluded. Choose a unique passphrase; it cannot be recovered.'),pass=field(backup,'Backup passphrase (12+ characters)','password');button(backup,'Create encrypted backup',async()=>{try{const result=await request('/backup',{passphrase:pass.value});message('Encrypted backup saved: '+result.path)}finally{pass.value=''}});grid.append(backup);
const restore=card('Restore to a new workspace','The target directory must not exist. Restored accounts require reconnecting; scheduled jobs stay cancelled. Current data is preserved.'),path=field(restore,'Encrypted backup absolute path'),target=field(restore,'New workspace absolute path'),password=field(restore,'Backup passphrase','password');button(restore,'Restore encrypted backup',async()=>{try{const result=await request('/restore',{path:path.value,target:target.value,passphrase:password.value});message('Restored to '+result.path+'. Set PUBLISHER_COMMUNITY_HOME to this directory and restart. Reconcile posts created since the backup before publishing.')}finally{password.value=''}});grid.append(restore)}
async function studio(grid){const setup=card('Your writing voice'),identity=field(setup,'Identity URN','text',studioIdentity);button(setup,'Load voice',()=>{studioIdentity=identity.value;render()});button(setup,'Enable learning',()=>post('/consent',{identity:identity.value,enabled:true}));button(setup,'Disable learning',()=>post('/consent',{identity:identity.value,enabled:false}));setup.append(el('p','Selected samples are analyzed by your current AI host. Imported writing is evidence, never instructions.'));const csv=field(setup,'LinkedIn Shares.csv','file');csv.accept='.csv';button(setup,'Import selected CSV',async()=>{if(csv.files[0])await post('/import',{identity:identity.value,csv:await csv.files[0].text()})});grid.append(setup);if(!studioIdentity)return;
const response=await fetch('/voice-context?identity='+encodeURIComponent(studioIdentity)),v=await response.json();if(!response.ok)throw Error(v.message);if(active!=='Voice Studio'||identity.value!==studioIdentity)return;const rules=card('Voice rules','Version '+v.version+' · '+v.heldOutSampleCount+' held-out examples. Evidence counts are not accuracy scores.');rules.classList.add('full');grid.append(rules);let entries=v.rules.map(r=>({...r}));const rows=el('div');rules.append(rows);
function draw(){rows.replaceChildren();for(const r of entries){const c=card(r.origin==='manual'?'Manual preference':r.basis),enabled=check(c,'Use this rule',r.enabled),text=field(c,'Writing instruction','textarea',r.instruction),kind=select(c,'Rule type',[['prefer','Prefer'],['avoid','Avoid']],r.kind),evidence=field(c,'Supporting sample IDs (one per line)','textarea',r.evidenceIds.join('\n'));enabled.onchange=()=>r.enabled=enabled.checked;text.oninput=()=>r.instruction=text.value;kind.onchange=()=>r.kind=kind.value;evidence.oninput=()=>r.evidenceIds=evidence.value.split('\n').filter(Boolean);const details=el('details');details.append(el('summary','View supporting examples ('+(r.supportingSamples||0)+')'));for(const s of r.evidence||[])details.append(el('pre',s.id+'\n'+s.text));c.append(details);button(c,'Remove rule',()=>{entries=entries.filter(x=>x!==r);draw()});rows.append(c)}}draw();button(rules,'Add manual preference',()=>{entries.push({id:crypto.randomUUID(),instruction:'',kind:'prefer',origin:'manual',enabled:true,evidenceIds:[]});draw()});button(rules,'Save voice rules',()=>post('/voice-rules',{identity:studioIdentity,profile:{expectedVersion:v.version,rules:entries.map(({id,instruction,kind,origin,enabled,evidenceIds})=>({id,instruction,kind,origin,enabled,evidenceIds}))}}));
const evidence=el('details');evidence.append(el('summary','Eligible training samples ('+v.trainingSamples.length+')'));for(const s of v.trainingSamples)evidence.append(el('pre',s.id+'\n'+s.text));rules.append(evidence);const legacy=(data.voices||[]).find(p=>p.identity===studioIdentity);if(legacy)rules.append(el('pre','Existing profile: '+legacy.summary));if(legacy||v.version)button(rules,v.frozen?'Unfreeze profile':'Freeze profile',()=>post('/voice',{identity:studioIdentity,action:v.frozen?'unfreeze':'freeze'}));button(rules,'Reset voice and samples',async()=>{if(confirm('Delete this identity’s voice rules, samples and comparisons?'))await post('/voice',{identity:studioIdentity,action:'reset'})});
const compare=card('Compare writing approaches','Ask Codex or Claude to produce three versions from the same brief. Paste them here and record your actual preference.');compare.classList.add('full');const brief=field(compare,'Brief','textarea'),generic=field(compare,'Generic draft','textarea'),current=field(compare,'Current voice','textarea'),revised=field(compare,'Revised voice','textarea'),preferred=select(compare,'My preferred version',[['none','No preference yet'],['generic','Generic'],['current','Current voice'],['revised','Revised voice']],'none'),feedback=field(compare,'Why / corrections','textarea');button(compare,'Save comparison',()=>post('/voice-comparison',{identity:studioIdentity,comparison:{brief:brief.value,generic:generic.value,current:current.value,revised:revised.value,preferred:preferred.value,feedback:feedback.value}}));grid.append(compare);for(const c of v.comparisons)grid.append(card(c.brief,'Preferred: '+c.preferred+'\n'+c.feedback));
const brand=card('Slide brand'),bg=field(brand,'Background','color','#F7F3E8'),fg=field(brand,'Text','color','#202B32'),accent=field(brand,'Accent','color','#B8432B'),footer=field(brand,'Footer');button(brand,'Save brand',()=>post('/brand',{identity:studioIdentity,brand:{background:bg.value,foreground:fg.value,accent:accent.value,footer:footer.value}}));grid.append(brand)}
load().catch(e=>message(e.message));
</script></html>`;
}
